### PR TITLE
Converting tabs to spaces in hstore migration

### PR DESCRIPTION
**Pull request by Frexuz**
:)

### CODE REVIEW

**Comment by palkan** [comment]
Thanks 😁

**Comment by Frexuz** [comment]
Hehe, just my mini-contribution for liking your project. We just implemented this, over paper_trail 👌

**Comment by palkan** [comment]
Glad to hear it)

Btw, could you, please, tell a little bit more about your use case and what was the main reason why you decided to use logidze over paper_trail? Just out of curiosity)

**Comment by Frexuz** [comment]
We just want to be able to track some changes, as part of an added level of logging for debugging/customer support, that we can easily see in an admin interface. We just chose logidze over paper_trail (used it before, and admin was really slow with millions of changesets) for performance reasons 👍

**Pull request merged**
