### PR TITLE
Add Sequel preliminary support

### LINKED ISSUE #28: Sequel support
Hi! It would be awesome if this gem supported not only ActiveRecord, but Sequel, too. I fiddled around with it the other day and it seems that providing Sequel support isn't hard.
What do you think about it? Should we make an adapter that would detect what abstraction is being used or should we make a separate gem for Sequel?

### PR DESCRIPTION
**Pull request by snacks02**
Thanks for the amazing library!

Fixes #28.

### What is the purpose of this pull request?

This is an attempt to get [the original Sequel preliminary support PR](https://github.com/palkan/logidze/pull/229) merged.

### What changes did you make? (overview)

Merged `master` from upstream, fixed conflicts, took the comments from the original PR into account.

### Is there anything you'd like reviewers to focus on?

The original PR is a brilliant piece of work, so I just wanted it merged so I could use upstream Logidze for a project. Not sure if there's anything else to say. :)

### Checklist

- [x] I've added tests for this change
- [x] I've added a Changelog entry
- [x] I've updated a documentation (Readme)

^ All of this was already done.

### CODE REVIEW

**Comment by ardecvz** [comment]
@sanks02 Hello, thank you for your work and for advancing the agenda!

This feature is indeed important, especially since there isn't a record tracker within the Sequel ecosystem.
We should certainly make a final push to make it into the gem.

There are just 2 things left to address:
1) We overlooked this comment - https://github.com/palkan/logidze/pull/229#discussion_r1163280458
The term "adapter" is a bit too generic. Considering we might support other databases like MySQL in the near future, we should rename it.
2) It might be a good idea to remove the strict dependency on ActiveSupport before the release (https://github.com/palkan/logidze/pull/229#discussion_r1169116900).
We only employ it for JSON serialization / deserialization as seen here:
https://github.com/palkan/logidze/pull/242/files#diff-fbdceda80b1b58da4bd608bbe7ee747e0d3569ecc991fbfcbd6688c02fc793ecR12-R32

The required steps would be:
1) Use the JSON encoding / decoding features provided by Sequel:
https://github.com/jeremyevans/sequel/blob/master/lib/sequel/core.rb#L169-L177
2) Run tests and set up two demo apps, one with ActiveRecord and the other with Sequel only. So we can ensure nothing is broken without ActiveSupport.

@sanks02, would you be interested to help with these tasks?
It would be a great help (also do not forget to add yourself to the contributors list in the README.md).

If you're busy, I'll hope to address these issues this week.

**Comment by sanks02** [comment]
@ardecvz Thanks for the heads up! It doesn't sound complicated, so I think I can do it.

**Comment by sanks02** [comment]
I'm halfway through adding `bundle exec rake spec:sequel` that doesn't depend on ActiveRecord and ActiveSupport.

There is a problem with generators depending on ActiveRecord. I'm not sure how to remove this dependency, so I'll remove the generators and associated specs for now.

Later we can see what [sequel-rails](https://github.com/TalentBox/sequel-rails) does, and try to do a similar thing to add the generators back. Does that sound good?

**Comment by sanks02** [comment]
@ardecvz Would you mind helping me from this point?

**Comment by palkan** [comment]
> I'm not aware of any lightweight alternatives to Rails generators

We can use plain [Thor](https://github.com/rails/thor); that would, probably, require adding a standalone `bin/logidze` CLI to perform the installation, etc.

> Remove generators for Sequel and create a detailed guide as intended by Sequel.

Another option is to add an application template via Ruby Bytes: https://github.com/palkan/rbytes

Basically, the same idea as using Thor but without dealing with CLIs, etc.

**Comment by sanks02** [comment]
It looks like rbytes does not support RSpec, which is used in this project.

**Comment by sanks02** [comment]
@ardecvz I added the Sequel generators back.

My knowledge of Rails generators, Thor and Ruby Bytes is limited, so if you don't mind picking the PR up, I'd appreciate it.

The issues with the current generators are:

- https://github.com/palkan/logidze/blob/caf7d9042d34bc1a4e289b3c4e32d6595646df5a/lib/generators/logidze/install/install_generator.rb#L95-L97
- https://github.com/palkan/logidze/blob/caf7d9042d34bc1a4e289b3c4e32d6595646df5a/lib/generators/logidze/model/model_generator.rb#L10

**Comment by sanks02** [comment]
How do you look at me adding the ActiveRecord/ActiveSupport dependency back, and having this merged?

**Comment by ardecvz** [comment]
Yes, I'm with your plan - adding support gradually is the only path forward right now.
Have we test the new version on both the ActiveRecord and Sequel dummy applications?
If that is the case, I believe @palkan will cut a release shortly after the merge.

**Comment by ardecvz** [comment]
And we should create an issue with future improvements - to keep a plan forward.

**Comment by sanks02** [comment]
Thanks. The branch is in a half-baked state right now. I'll fix it and let you know when it can be reviewed.

**Comment by sanks02** [comment]
Should be ready for a review.

Suggestions from the original PR have been taken into account and small changes have been made to further separate Logidze from ActiveSupport.

I didn't finish adding a separate Sequel demo as it would be impossible to test if it works without ActiveRecord anyway, but I mentioned it in [the newly created issue](https://github.com/palkan/logidze/issues/244).

[The difference between this and the original PR.](https://github.com/palkan/logidze/files/13972141/diff.tar.gz) I hope this helps. Let me know if anything else is needed. :)

**Comment by palkan** [comment]
Thanks @sanks02!

Please, take a look at the RuboCop offenses (look legit) and RSpec failures.

@ardecvz Waiting for your approval 🙂 (and the green CI, of course)

**Comment by sanks02** [comment]
Sorry about that, I may have accidentally tested `bundle exec rake` on a wrong branch. Fixed now.

**Comment by sanks02** [comment]
[diff.tar.gz](https://github.com/palkan/logidze/files/13984223/diff.tar.gz)

**Comment by sanks02** [comment]
I've started using this in a real world application and it seems to work just fine

**Comment by palkan** [comment]
@sanks02 Thanks!

@ardecvz I'm still waiting for your pair of eyes 👀

**Pull request closed without merging**
