### PR TITLE
Add API to nullify log_data column

### PR DESCRIPTION
**Pull request by Arkweid**
#108 This commit add class method .reset_log_data for nullify
association and instance method #reset_log_data for nullify
single record.

### CODE REVIEW

**Comment by Arkweid** [comment]
@palkan CHANGELOG.md updated

**Comment by palkan** [comment]
@Arkweid Let's fix specs (code examples in readme/changelog are not valid Ruby)

**Comment by Arkweid** [comment]
@palkan Fixed.

**Comment by palkan** [comment]
Thanks!

**Pull request merged**
